version: '3.9'

services:
  
  electro-database:
    container_name: electro-database
    image: mysql:8.0
    cap_add:
      - SYS_NICE
    environment:
      MYSQL_ROOT_PASSWORD: 12345
      MYSQL_DATABASE: electro
      LANG: C.UTF-8 
    ports:
      - 3306:3306
    volumes:
      - storage:/var/lib/mysql
      - ./electro-server/src/main/resources/address.sql:/docker-entrypoint-initdb.d/init.sql
    command: --sql_mode="STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION" --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci --general-log=1 --general-log-file=/tmp/mysql-general-log.log
    healthcheck:
      # Reference: https://stackoverflow.com/a/74905088
      test: 'cat /tmp/mysql-general-log.log | grep "Tcp port: 3306"'
      interval: 5s
      timeout: 30s
      retries: 20

volumes:
  storage:
    driver: local


